services:
  - type: web
    name: image-video-modifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webappimagevidmodifier:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-server
          property: connectionString
    plan: free

  - type: redis
    name: redis-server
    ipAllowList: [] # optional (accepts all)
    plan: free
