services:
  - type: web
    name: image-video-modifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webappimagevidmodifier:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-server
          property: connectionString
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: OUTPUT_FOLDER
        value: /tmp/outputs
      - key: FFMPEG_PATH
        value: /usr/bin/ffmpeg
    plan: free

  - type: redis
    name: redis-server
    ipAllowList: []
    plan: free 
